# Generated by Django 5.0.2 on 2024-02-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_alter_mysocialuser_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysocialuser',
            name='profileimg',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
