# Generated by Django 5.0.2 on 2024-02-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0010_alter_mysocialuser_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysocialuser',
            name='profileimg',
            field=models.ImageField(default='profile_picture.jpeg', upload_to='profiles/'),
        ),
    ]
