# Generated by Django 5.0.2 on 2024-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0011_alter_mysocialuser_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_posts/'),
        ),
    ]
