# Generated by Django 5.0.2 on 2024-05-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0012_alter_posts_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='MySocialUser',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
